### ISSUE TITLE
Notification not working with Chrome Native Notification and GNotifier plugins for Firefox/Thunderbird

### ISSUE THREAD

**Issue by emhaye** [linuxdeepin/deepin-notifications#10]

**Comment by DasJott** [comment]
This is true, I also experience this.

The cause is, that GNotifier checks for the capabilities and there seems to be a typo in the deepin version of notify:

org.freedesktop.Notifications.GetCapbilities

should be 

org.freedesktop.Notifications.GetCap**a**bilities

**Comment by bebehei** [comment]
The issue got fixed in 58cee26c1375868af3b240cb5ed2bfddf73e74db

**Comment by Filnor** [comment]
> The issue got fixed in [58cee26](https://github.com/linuxdeepin/deepin-notifications/commit/58cee26c1375868af3b240cb5ed2bfddf73e74db)

So this issue should be closed, right?

**Comment by bebehei** [comment]
Yes.

**Comment by emhaye** [comment]
Fixed

Thank you
